name: 'Terraform'


on:
  push:
    branches:
    - main
  pull_request:
 
jobs:
  terraform:
    name: 'Terraform'
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      TF_VAR_storage_access_key: ${{ secrets.STORAGE_ACCESS_KEY }}
      TF_VAR_storage_connection_string: ${{ secrets.STORAGE_CONNECTION_STRING }}
    runs-on: ubuntu-latest
    environment: production
 
    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash
 
    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v2
         
    - name: 'Setup Terraform'
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.3.0

    - name: 'Terraform Init'
      working-directory: ./infra
      run: terraform init

    - name: 'Terraform Plan'
      working-directory: ./infra
      run: terraform plan

    - name: 'Terraform Apply'
      if: github.ref == 'refs/heads/main'
      working-directory: ./infra
      run: terraform apply -auto-approve
